services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-api-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: php-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: php-api-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
